### ISSUE TITLE
Ordenação nas listagens - Marca e Modelo

### ISSUE THREAD

**Issue by cassinodari** [douglasfkln/carwash-company#11]
Passos para reproduzir o erro:
Fazer o cadastro de um veículo e selecionar o campo de Marca.
Fazer o cadastro de um veículo e selecionar o campo de Modelo.

Comportamento Atual + Evidência:
Aplicação não está ordenando os itens na listagem.
[Imagem 1](https://uploaddeimagens.com.br/imagens/Ci9csM0)
[Imagem 2](https://uploaddeimagens.com.br/imagens/_NzxFSI)

Comportamento Esperado:
Realizar a ordenação dos itens em ordem alfabética.

Dados utilizados para reproduzir o problema:

**Comment by douglasfkln** [comment]
A ordenação é melhor por recomendado como está, se for em ordem alfabética dificulta a usabilidade
