### ISSUE TITLE
Visualização de Serviço de um cliente

### ISSUE THREAD

**Issue by cassinodari** [douglasfkln/carwash-company#12]
Passos para reproduzir o erro:
Acessar um serviço criado para um cliente.

Comportamento Atual + Evidência:
Não está carregando o mapa e além disso está cortando a escrita conforme mostra a imagem a seguir.
[Imagem 1](https://uploaddeimagens.com.br/imagens/fkfWakM)

Comportamento Esperado:
Carregar o mapa com a escrita legível.

Dados utilizados para reproduzir o problema:

**Comment by douglasfkln** [comment]
Alterado forma de renderizar mapa, agora está funcionando pra android...
Quebrado linha de endereço caso precise.
Melhorias na tela de solicitações
