### ISSUE TITLE
Agendamento de serviço

### ISSUE THREAD

**Issue by cassinodari** [douglasfkln/carwash-company#13]
Passos para reproduzir o erro:
Cadastrar um agendamento e em seguida voltar para a mesma tela de cadastro de agendamento

Comportamento Atual + Evidência:
Os campos não estão sendo zerados.

Comportamento Esperado:
Deve zerar os valores após realizar o cadastro.

Dados utilizados para reproduzir o problema:

**Comment by douglasfkln** [comment]
Zerado dados após salvar fomulário
