### ISSUE TITLE
Visualização da senha

### ISSUE THREAD

**Issue by cassinodari** [douglasfkln/carwash-company#3]
Passos para reproduzir o erro:
Acessar o aplicativo depois que o e-mail já foi validado.

Comportamento Atual + Evidência:
Usuário precisa digitar a senha novamente sem poder visualizar o que está de errado com ela, pensando em um usuário que possui senha extensa a usabilidade fica comprometida.
[Visualização da Senha](https://uploaddeimagens.com.br/imagens/Vr_7Fic)

Comportamento Esperado:
Adicionar opção para usuário poder visualizar a senha digitada.

Dados utilizados para reproduzir o problema:

**Comment by douglasfkln** [comment]
Adicionado icone para visualizar senha no cadastro de empresa, no login e em Meu Perfil
