### ISSUE TITLE
Adicionar máscara

### ISSUE THREAD

**Issue by cassinodari** [douglasfkln/carwash-company#4]
Passos para reproduzir o erro:
Realizar o cadastro de uma empresa e preencher o campo **telefone**.
Realizar o cadastro de um cliente e preencher o campo **telefone**.

Comportamento Atual + Evidência:
O campo telefone está sem a máscara.
[Imagem 1](https://uploaddeimagens.com.br/imagens/OoYYBvU)

O campo telefone está sem a máscara.
[Imagem 2](https://uploaddeimagens.com.br/imagens/xZ1VeMc)

Comportamento Esperado:
Adicionar a máscara no campo input do telefone.

Dados utilizados para reproduzir o problema:

**Comment by douglasfkln** [comment]
Adicionado mascaras no cadastro da empresa e de clientes
