### ISSUE TITLE
Tela inicial - Dados do perfil

### ISSUE THREAD

**Issue by cassinodari** [douglasfkln/carwash-company#6]
Passos para reproduzir o erro:
Acessar o aplicativo e ir até a tela inicial do aplicativo.

Comportamento Atual + Evidência:
Até que o usuário não informa a foto de perfil, a aplicação está ficando conforme mostra a imagem abaixo.
[Imagem 1](https://uploaddeimagens.com.br/imagens/S8DaRfc)

Comportamento Esperado:
Ver possibilidade de adicionar uma imagem conforme esta:
[Imagem 2](https://uploaddeimagens.com.br/imagens/qPYHi3o)
Se não for possível, ver a possibilidade de retirar a informação da imagem até que o usuário faça a inserção dessa informação.

Dados utilizados para reproduzir o problema:

**Comment by douglasfkln** [comment]
Retirado foto de perfil temporariamente, será uma feature para o futuro
